disabled_rules:
  - trailing_whitespace
  - line_length
  - large_tuple
  - identifier_name
  - todo
  - function_body_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - force_cast
  - file_length
  - type_body_length
  - nesting
  - inclusive_language
excluded:
  - Carthage
  - Deploy
  - build
type_name:
  max_length: 50
  excluded:
    - D
    - T # generic typealias usually
function_parameter_count:
  warning: 7