name: Build

on:
  push:
    branches: 
      - develop
  pull_request:

jobs:
  build:
    name: Library Build
    runs-on: macos-14
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set proper xcode version
        run: sh ./scripts/xcodeselect.sh
      - name: Run build script
        run: sh ./scripts/build.sh