name: PodLint

on:
  push:
    branches: 
      - develop
  pull_request:

jobs:
  podlint:
    name: Pod Lib Lint
    runs-on: macos-14
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set proper xcode version
        run: sh ./scripts/xcodeselect.sh
      - name: Lint
        run: pod lib lint --allow-warnings